version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always
  # app:
  #   build: .
  #   command: npm start
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_HOST: postgres
  #     DATABASE_USER: your_username
  #     DATABASE_PASSWORD: your_password
  #     DATABASE_NAME: library_management
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   restart: always